config/routes.rb
Rails.application.routes.draw do

  resources :maps

  root 'maps#index'

    get 'maps' => 'maps#index'
    post 'maps' => 'maps#create'
    get 'about' => 'maps#about' 
    get 'contact' => 'maps#contact'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
	attr_accessor :latitude, :longitude, :title

	def initialize(options={})
		@lat = options["latitude"]
		@long = options["longitude"]
		@title = options["title"]

	end

end

app/models/intermediate.rb
class Intermediate < ActiveRecord::Base
	attr_accessor :lat, :long, :title

	def initialize(options={})
		@lat = options["lat"]
		@long = options["long"]
		@title = options["title"]

	end

	
end

app/models/my_location.rb
class MyLocation < ActiveRecord::Base
	attr_accessor :lat, :long	

	def initialize(options={})
		@lat = options[:lat]
		@long = options[:long]
	end

end

app/models/points_of_interest.rb
class PointsOfInterest < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
require 'json'
require 'net/http'

class MapsController < ApplicationController
  def index
    @my_location = MyLocation.new({lat: params["lat"], long: params["long"]})

    @points_of_interest = PointsOfInterest.all[1..30]

    @destination = Destination.new({latitude: params[:latitude], longitude: params[:longitude]})

    @address = params[:search] ||= 'San Francisco'

    # response = HTTParty.get('https://maps.google.com/maps/api/geocode/json?address=' + @address.gsub(" ", "_") + '&sensor=false&key=' + ENV["GOOGLE_SERVER_KEY"])

    response = HTTParty.get("http://query.yahooapis.com/v1/public/yql?q=SELECT%20*%20FROM%20geo.places%20WHERE%20text=%22" + @address.gsub(" ", "") + "%22%20and%20placeTypeName=%22Town%22")


# url = URI.parse('http://maps.google.com/maps/api/geocode/json?address=' + @address + '&sensor=false')
# req = Net::HTTP::Get.new(url.to_s)
# res = Net::HTTP.start(url.host, url.port) {|http|
#   http.request(req)
# }

#  puts res.body


    response = Hash.from_xml(response.body)
    @latitude = response["query"]["results"]["place"]["centroid"]["latitude"] || 1
    @longitude = response["query"]["results"]["place"]["centroid"]["longitude"] || 2

  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/_header.html.erb
<div class="navbar-fixed">
  <nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <ul class="left hide-on-med-and down">
        <li> <a id="logo"><%= link_to "STUMBLRRR", root_path %></a></li>
      </ul>
      <ul class="right hide-on-med-and-down">
        <li><a href="about">ABOUT</a></li>
        <li><a href="https://github.com/huangkc/stumblrrr">GITHUB</a></li>

      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">Navbar Link</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stumblrrr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!--   <link href="../../assets/stylesheets/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/> -->
  <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500italic,500,700,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&libraries=geometry&language=&hl=&region="></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/js-marker-clusterer/1.0.0/markerclusterer.js"></script>

<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<script src="
https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body style="background-color:#F1F1F1">

<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/maps/about.html.erb
<div class="space"></div>
<div class="row">
  <div class="about-page">

  	<div class="col-md-3"></div>
  	<div class="col-md-6">

			<% provide(:title, 'About') %>
			<p id="about">
			Built with Rails backend and Bootstrap frontend, this application allows users to find artistic venues in the city of San Francisco. Submitted to the Dev Bootcamp Civic Hackathon in January 2016. 
			</p>

		</div>
  	<div class="col-md-3"></div>
	</div>
</div>

app/views/maps/index.html.erb
<div style="padding-top:8px" class="col-md-6 col-md-offset-3 text-center">
  <%= form_tag(maps_path, :method => "get", class: "navbar-form form-lg", id: "search-form") do %>
    <%= hidden_field_tag :sort_option, :search %>
    <%= text_field_tag :search, params[:search], class: "btn-block btn-border btn-lg", placeholder: "Where do you want to go ?" %>

<!--       <div style="margin-top:15px" class="btn btn-lg btn-danger btn-border" type="submit"><b style="font-size:bold; letter-spacing:-1px; font-size:30px"><i>STUMBLRRR</i></b></div> -->
      <div id="instruction">
        <p>Interested in the arts in San Francisco? Click the locations in green for venues that might interest you!</p>
      </div>
  <% end %>
</div>

<div id="map_canvas"></div>
<div class="space"></div>
<footer class="page-footer white">
  <div class="container center">copyright 2016</div>
</footer>
<script>
function buildMap(coords){
  var mapStyle =[
  {
    "featureType": "all",
    "elementType": "labels.text.fill",
    "stylers": [
    {
      "saturation": 36
    },
    {
      "color": "#000000"
    },
    {
      "lightness": 40
    }
    ]
  },
  {
    "featureType": "all",
    "elementType": "labels.text.stroke",
    "stylers": [
    {
      "visibility": "on"
    },
    {
      "color": "#000000"
    },
    {
      "lightness": 16
    }
    ]
  },
  {
    "featureType": "all",
    "elementType": "labels.icon",
    "stylers": [
    {
      "visibility": "off"
    }
    ]
  },
  {
    "featureType": "administrative",
    "elementType": "geometry.fill",
    "stylers": [
    {
      "color": "#000000"
    },
    {
      "lightness": 20
    }
    ]
  },
  {
    "featureType": "administrative",
    "elementType": "geometry.stroke",
    "stylers": [
    {
      "color": "#000000"
    },
    {
      "lightness": 17
    },
    {
      "weight": 1.2
    }
    ]
  },
  {
    "featureType": "landscape",
    "elementType": "geometry",
    "stylers": [
    {
      "color": "#000000"
    },
    {
      "lightness": 20
    }
    ]
  },
  {
    "featureType": "poi",
    "elementType": "geometry",
    "stylers": [
    {
      "color": "#000000"
    },
    {
      "lightness": 21
    }
    ]
  },
  {
    "featureType": "road.highway",
    "elementType": "geometry.fill",
    "stylers": [
    {
      "color": "#000000"
    },
    {
      "lightness": 17
    }
    ]
  },
  {
    "featureType": "road.highway",
    "elementType": "geometry.stroke",
    "stylers": [
    {
      "color": "#000000"
    },
    {
      "lightness": 29
    },
    {
      "weight": 0.2
    }
    ]
  },
  {
    "featureType": "road.arterial",
    "elementType": "geometry",
    "stylers": [
    {
      "color": "#000000"
    },
    {
      "lightness": 18
    }
    ]
  },
  {
    "featureType": "road.local",
    "elementType": "geometry",
    "stylers": [
    {
      "color": "#000000"
    },
    {
      "lightness": 16
    }
    ]
  },
  {
    "featureType": "transit",
    "elementType": "geometry",
    "stylers": [
    {
      "color": "#000000"
    },
    {
      "lightness": 19
    }
    ]
  },
  {
    "featureType": "water",
    "elementType": "geometry",
    "stylers": [
    {
      "color": "#000000"
    },
    {
      "lightness": 17
    }
    ]
  }
  ];



  var contentString = 'Hello'


  handler = Gmaps.build('Google');




  handler.buildMap({

    provider: {
      disableDefaultUI: true,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      styles: mapStyle,
      zoom: 5,


// pass in other Google Maps API options here
},
internal: {
  id: 'map_canvas'

}
},

function(){
  markers = handler.addMarkers([

// Sample todo marker to iterate over


<% @points_of_interest.each do |point| %>

{
  "lat": <%= point.lat %>,
  "lng": <%= point.long %>,
  "picture": {
    "url": "http://s29.postimg.org/7acw7mleb/todo.png",
    "width":  32,
    "height": 32
  },


  "infowindow": '<div id="content">'+
      '<div id="siteNotice">'+
      '</div>'+
      '<h1 id="firstHeading" class="firstHeading">'+'<%= point.title %>'+'</h1>'+
      '<div id="bodyContent">'+
      '<p><b>By ' + '<%= point.artist %>' + '</b></p>'

},
<% end %>


// Sample arrival marker (only one of these)
{
  "lat": <%= @latitude %>,
  "lng": <%= @longitude %>,
  "picture": {
    "url": "http://s18.postimg.org/cdenuliv9/arrival.png",
    "width":  32,
    "height": 32
  },
  "infowindow": "<h1 style='color:red'>You go here!</h1>"
},

// Sample arrival marker (only one of these)
{
  "lat": coords.lat,
  "lng": coords.long,
  "picture": {
    "url": "http://s14.postimg.org/moj60jusd/start.png",
    "width":  32,
    "height": 32
  },
  "infowindow": "<h1 style='color:blue'>You are here!</h1>"
},

]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
}

</script>


<script>
$(document).ready(function(){
  getLocation();
})

function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);

  } else {
// x.innerHTML = "Geolocation is not supported by this browser.";
}
}
function showPosition(position) {
  var coords = {
    lat: position.coords.latitude,
    long: position.coords.longitude

  }
  buildMap(coords);
}
</script>